sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t me/docker-react -f Dockerfile.dev .
#
script:
  - docker run -e CI=true me/docker-react npm run test -- --coverage

